apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    run: model-service
spec:   
  type: NodePort
  selector:
    run: model
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
    